### ISSUE TITLE
Package not working with Python 3.10

### ISSUE THREAD

**Issue by Tchekda** [noirbizarre/flask-restplus#812]
### **Code**

```python
from flask_restplus import Api, Resource, fields
```

### **Repro Steps** (if applicable)
1. Install Python 3.10 
2. Try to import flask_restplus
3. Broken!

### **Expected Behavior**
A description of what you expected to happen.

### **Actual Behavior**

Error during import

### **Error Messages/Stack Trace**

```
 * Serving Flask app "inputs.api.app" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 119-734-217
127.0.0.1 - - [01/Nov/2021 23:36:45] "POST /upload/LYO031011 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "PROJECT_DIR/inputs/api/app.py", line 2, in <module>
    from flask_restplus import Api, Resource, fields
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask_restplus/__init__.py", line 4, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask_restplus/reqparse.py", line 19, in <module>
    from .model import Model
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask_restplus/model.py", line 8, in <module>
    from collections import OrderedDict, MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (PYTHON_PATH/lib/python3.10/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask/cli.py", line 338, in __call__
    self._flush_bg_loading_exception()
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask/cli.py", line 326, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask/cli.py", line 314, in _load_app
    self._load_unlocked()
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing "inputs.api.app", an ImportError was raised:

Traceback (most recent call last):
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "PROJECT_DIR/inputs/api/app.py", line 2, in <module>
    from flask_restplus import Api, Resource, fields
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask_restplus/__init__.py", line 4, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask_restplus/reqparse.py", line 19, in <module>
    from .model import Model
  File "PROJECT_DIR/venv/lib/python3.10/site-packages/flask_restplus/model.py", line 8, in <module>
    from collections import OrderedDict, MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (PYTHON_PATH/lib/python3.10/collections/__init__.py)
```

### **Environment**
- Python version: `Python 3.10.0rc1`
- Flask version: `1.1.4`
- Flask-RESTPlus version: `0.13.0`

### **Additional Context**

Working in 3.9 but not in 3.10

**Comment by Tchekda** [comment]
I'm stupid, sorry. 
> This project has been forked to Flask-RESTX and will be maintained by by the python-restx organization. Flask-RESTPlus should be considered unmaintained.
